version: 2
jobs:
  build:
    docker:
      - image: basph/pylint-airflow-ci:latest
    steps:
      - checkout
      - run:
          name: Pip install Pylint-Airflow package
          command: |
            pip install .
      - run:
          name: Check Black formatting
          command: |
            find . -name '*.py' | xargs black --check --line-length=100
      - run:
          name: Check Pylint
          command: |
            find . -name '*.py' | xargs pylint --output-format=colorized
      - run:
          name: Validate Pylint-Airflow message IDs
          command: |
            ls -lah
            pwd
            python scripts/validate_message_ids.py
      - run:
          name: Run tests
          command: |
            pytest tests/
