version: 2
jobs:
  build:
    docker:
      - image: basph/pylint-airflow-ci:latest
    steps:
      - checkout
      - run:
          name: Pip install Pylint-Airflow package
          command: |
            pip install .
      - run:
          name: Check Black formatting
          command: |
            make black
      - run:
          name: Check Pylint
          command: |
            make pylint
      - run:
          name: Validate Pylint-Airflow message IDs
          command: |
            make validate_message_ids
      - run:
          name: Run tests
          command: |
            make pytest
